### ISSUE TITLE
Develop the signup controller for Hitch

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#1]
Develop the backend signup route for Hitch, a critical functionality to enable user registration on our collaborative platform. Contributors are tasked with creating a secure and efficient endpoint that handles user signup requests.

Tasks:

1. Design and implement the signup route in the backend, allowing users to register with the following information (check user schema for reference):
Full Name
Email Address
Username
Password
2. Integrate robust validation for input data to ensure data integrity and security.
3. Some functions are already provided in user schema for hashing and JWT generation.
4. Set up error handling to provide meaningful feedback for different scenarios, such as existing user accounts or invalid input, etc.
5. When a user signs in and their details are added to the database, you can generate a JWT (JSON Web Token) for authentication and send it back to the client as a cookie.
6. Test the signup route thoroughly to ensure it functions correctly under various conditions.

Once completed, submit a pull request with the code, and include relevant documentation for integration.
Time: 48 hours.

Please comment to claim the issue.

**Comment by PranavBansal21** [comment]
claim
