### ISSUE TITLE
Generate random password

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#106]
Write the function in ```generate.utils.js``` to generate random password of given size.

This is open for all issue.
No need to claim.

**Comment by DikshantK2004** [comment]
Claim

**Comment by automatefreely** [comment]
this issue is open @DikshantK2004

**Comment by criticic** [comment]
>This is open for all issue.
>No need to claim.
?

**Comment by Apoorv012** [comment]
claim
