### ISSUE TITLE
Send messages controllers

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#107]
Write the controller function to send message in a subchannel. You will need to add respective checks in the function. The function should be written in controllers > message.controller.js. The request structure is present in APIEndPoint.md [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#send-message).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user, workspace, channel, subchannel object are present in request and are all verified.
2. User is member of subchannels
3. No need to worry about image and socketio in this issue

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by Jarviss77** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @Jarviss77

**Comment by Jarviss77** [comment]
@automatefreely bhaijaan points nahi daale apne
