### ISSUE TITLE
Add initialize socket function

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#109]
Write/Complete the function in ```index.socket.js``` to initialize the socket IO.

- [ ] Add try catch and give suitable error message
- [ ] Verify the JWT present in cookies  -> for this you can refer to ```auth.middleware.js``` to know the structure
- [ ] Add event listeners on all the event as per the event Enums present in ```chatEvents.enums.js```

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by DikshantK2004** [comment]
Claim

**Comment by WadadParker** [comment]
Claim

**Comment by DikshantK2004** [comment]
@automatefreely you assigned me the random string issue, but that is not supposed to be claimed, can you assign me this one?

**Comment by Jarviss77** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004
