### ISSUE TITLE
New Workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#11]
Write the controller function to create a new workspace. You will need to add respective checks in the function. The function should be written in ```controllers > workspace.controller.js```. The request structure is present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#create-workspace).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

Make sure to **pull** before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by criticic** [comment]
.claim

**Comment by criticic** [comment]
claim

On 14-Dec-2023, at 2:42 PM, Swaroop Dora ***@***.***> wrote:



Write the controller function to create a new workspace. You will need to add respective checks in the function. The function should be written in controllers > workspace.controller.js. The request structure is present here<https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#create-workspace>.

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

All the Best!!

**Comment by automatefreely** [comment]
assigned to @criticic
