### ISSUE TITLE
Route to Get SubChannels

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#111]
Write and test route for getting all the SubChannel present in the channel.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment claim to work on this issue.
Any problem ping me on discord or comment.

**Comment by Jarviss77** [comment]
Claim

**Comment by Harshal5167** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Harshal5167
