### ISSUE TITLE
Multer middleware for image upload

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#112]
Write the Multer middleware in ```fileUpload.middleware.js```  for image upload.
All the images need to be stored in ```src/public/images```.
Make name of file is unique.
Also format the name of file received.
Write a diskStorage.

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by criticic** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic
