### ISSUE TITLE
Controller and route for adding image for user

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#119]
1. ![image](https://github.com/opencodeiiita/Hitch-Backend/assets/105218991/f315d7c9-6d55-4ea7-add6-c12f53d3f460)
This is request format.
2. Use isAuthorized and upload middleware
3. write route and controller in respective files
4. test and show the screenshot of working api

Any problem or issue comment or join in discord.
comment to claim the issue.

**Comment by rnavaneeth992** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @rnavaneeth992
