### ISSUE TITLE
Route to sendMessage

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#122]
Write and test route for sending message in the SubChannel.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment claim to work on this issue.
Any problem ping me on discord or comment.

**Comment by TheDivineAurora** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
@TheDivineAurora you have a open issue already!

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004

**Comment by Aditya2174** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Aditya2174
