### ISSUE TITLE
Email verification

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#123]
- [ ] Add a field in user model to check if the user is verified or not.
- [ ] Add a method to the user model to send verification email using any template provided with a link having unique verification id.
- [ ] You can store the verification id and the generation time as fields in user.
- [ ] Modify the registration API and call this method.
- [ ] So working screenshots.

Note:
1. You can use the function provided for sending email.
2. You can modify any things if needed.

Comment to claim.

**Comment by TheDivineAurora** [comment]
claim

**Comment by TheDivineAurora** [comment]
pr posted for other issue btw

**Comment by automatefreely** [comment]
Assigned to @TheDivineAurora
