### ISSUE TITLE
Update workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#15]
Write the controller function to update an existing workspace.  The function should be written in ```controllers > workspace.controller.js```. The request structure is given [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#update-workspace).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses. Give correct error responses for workspaceId already exist. Also check for existence of the workspace.

All the error responses' message needed to be specific to the cause of error.

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by inviBeast** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic
