### ISSUE TITLE
Delete Workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#16]
Write the controller function to **delete** an **existing workspace**. The function should be written in ```controllers > workspace.controller.js```. The request structure is given [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#delete-workspace).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses. Give correct error responses for workspaceId already exist. Also check for existence of the workspace. User should be creator to delete the workspace.

All the error responses' message needed to be specific to the cause of error.

>Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by Karansenpai** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic
