### ISSUE TITLE
Develop the login controller for Hitch

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#2]
Implement a Sign-in API to enable users to authenticate and access our platform's services securely. This API will serve as the gateway for users to log in using their credentials and obtain the necessary authorization to interact with our system.

Key Requirements:

1. **User Authentication:** The API should authenticate users by validating their credentials, such as email and password.
2. **Secure Authentication:** Some function are already provided in user models for better and easier implementation, like comparePassword, generateToken etc.
3. **Error Handling:** Ensure clear and descriptive error messages for different scenarios (e.g., incorrect credentials, expired session).
4. **Session Management:** Implement a mechanism for managing user sessions securely, including session expiration and token generation.

All response needed to be sent in the following JSON format
```
{
    result: false,
    error: "${For debugging}",
    message: "${Message to be displayed to user as a toast}"
}
```

Any question you can comment.

Once completed, submit a pull request with the code, and include relevant documentation for integration.
Time: 48 hours.

Please comment to claim the issue.

**Comment by TheDivineAurora** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @TheDivineAurora

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
@TheDivineAurora Updates??

**Comment by automatefreely** [comment]
This issue is now open for claim.

**Comment by DikshantK2004** [comment]
Claim

**Comment by automatefreely** [comment]
The issue is assigned now to @DikshantK2004

**Comment by coderatiiita** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by pahalsrivastava** [comment]
claim
