### ISSUE TITLE
Development of User Auth Middleware for Secure Access Control

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#3]
Assume the following things:
1. The JWT token will be provided in the cookies. If not check for it available in the req.token
2. The decrypted JWT will contain the **user id** auto created by moongDB.

For sending response use utils > responseCode.utils.js

**Store the userId of the user in req.userId**
**Store the complete user object in req.user**

Any question you can comment.

Once completed, submit a pull request with the code, and include relevant documentation for integration.

Please comment to claim the issue.

**Comment by Rudreshdabre12** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Rudreshdabre12

**Comment by automatefreely** [comment]
@Rudreshdabre12 any updates.

**Comment by DikshantK2004** [comment]
claim

**Comment by Rudreshdabre12** [comment]
> @Rudreshdabre12 any updates.

Working on middleware authorization

**Comment by coderatiiita** [comment]
claim

**Comment by chandra1899** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by automatefreely** [comment]
@Rudreshdabre12 are you still working on it?

**Comment by Rudreshdabre12** [comment]
i have currently made a PR on middleware and email verification template

**Comment by Rudreshdabre12** [comment]
I already made a PR

**Comment by automatefreely** [comment]
@Rudreshdabre12 are you still on this issue?

**Comment by DikshantK2004** [comment]
Claim

**Comment by automatefreely** [comment]
This issue is open for claim

**Comment by Ashutosh9993** [comment]
Claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by Karansenpai** [comment]
claim

**Comment by Karansenpai** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Ashutosh9993

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
@Ashutosh9993  status?? any problem comment

**Comment by DikshantK2004** [comment]
claim

**Comment by automatefreely** [comment]
this issue is open for claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004

**Comment by sanjana-19o8** [comment]
claim
