### ISSUE TITLE
Middleware to ensure User is admin of workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#30]
# Middleware for Workspace Admin Check

1. Create a file in middleware folder named isWorkspaceAdmin.middleware.js
2. write a middleware assuming the following request body
  
    ```json
   {
       "user": "mongoDB object of user"
   }
   ```

   and request param

    ```json
    {
         "id": "String"           -> MongoId of Workspace
    }
    ```

3. Assume user is already checked. You need to check Workspace exist or not.
4. If the user is not admin, send a response with status code 403 and message "You are not authorized to perform this action"
5. Add the workspace to the request body.
6. If the user is admin, call next() to pass the request to the next middleware.

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by DikshantK2004** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004

**Comment by coderatiiita** [comment]
claim
