### ISSUE TITLE
Create Channel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#32]
Write the controller function to create a new channel in workspace. You will need to add respective checks in the function. The function should be written in controllers > channel.controller.js. The request and response structure are present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#create-channel).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user and workspace object are present in request and are all verified.
2. User is admin of workspace

**Also check all the details are in correct format and values.**

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by DikshantK2004** [comment]
Claim

**Comment by WadadParker** [comment]
claim

**Comment by automatefreely** [comment]
@DikshantK2004 you already have a issue assigned

**Comment by automatefreely** [comment]
Assigned to @WadadParker

**Comment by coderatiiita** [comment]
claim
