### ISSUE TITLE
Update channel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#33]
Write the controller function to update details of the channel. You will need to add respective checks in the function. The function should be written in controllers > channel.controller.js. The request structure is present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#update-channel).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user, workspace and channel object are present in request and are all verified.
2. User is admin of workspace

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by criticic** [comment]
claim

**Comment by WadadParker** [comment]
claim

**Comment by AngadManroy** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic

**Comment by coderatiiita** [comment]
claim
