### ISSUE TITLE
Delete Channel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#34]
Write the controller function to delete a channel. You will need to add required checks in the function. The function should be written in controllers > channel.controller.js. The request structure is present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#delete-channel).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user, workspace and channel object are present in request and are all verified.
2. User is admin of workspace

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by criticic** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by WadadParker** [comment]
claim

**Comment by AngadManroy** [comment]
claim

**Comment by automatefreely** [comment]
@criticic @DikshantK2004 @WadadParker you are already assigned an issue

**Comment by automatefreely** [comment]
Assigned to @AngadManroy

**Comment by coderatiiita** [comment]
claim

**Comment by automatefreely** [comment]
@AngadManroy Are you working on this issue? if any problem regarding this issue -> comment

**Comment by AngadManroy** [comment]
Yes, I'm working on it. I will complete it within the 2 day day deadline.

**Comment by automatefreely** [comment]
This issue is open for claim!

**Comment by criticic** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic

**Comment by Jarviss77** [comment]
Claim
