### ISSUE TITLE
Middleware for member of the Workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#44]
# Middleware for Workspace member Check

1. Create a file in middleware folder named isWorkspaceMember.middleware.js
2. write a middleware assuming the following request body
  
    ```json
   {
       "user": "mongoDB object of user"
   }
   ```

   and request param

    ```json
    {
         "id": "String"           -> MongoId of Workspace
    }
    ```

3. Assume user is already checked. You need to check Workspace exist or not.
4. If the user is not member, send a response with status code 403 and message "You are not authorized to perform this action"
5. Add the workspace to the request body.
6. If the user is member, call next() to pass the request to the next middleware.

> Tip: A user is consider a member of a workspace if he is member of at least a channel belonging to it. Admin is a member also.

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by rnavaneeth992** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @rnavaneeth992

**Comment by Jarviss77** [comment]
Claim
