### ISSUE TITLE
Add user to channel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#47]
Write the controller function to add user to channel. You will need to add respective checks in the function. The function should be written in controllers > channel.controller.js. The request structure is present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#add-user-to-channel).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user, workspace and channel object are present in request and are all verified.
2. User is admin of workspace

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by WadadParker** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Jarviss77
