### ISSUE TITLE
Write a function to send Email to users

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#5]
In the file [utils > sendMail.utils.js](https://github.com/opencodeiiita/Hitch-Backend/blob/main/src/utils/sendMail.utils.js) write a function that takes three arguments: email, body, html and sends an email with the body and HTML to the email provided in the argument.

For this, you can use the library nodemailer. The email should be sent using a Gmail account. For testing you will need to create an [App Password](https://support.google.com/accounts/answer/185833?hl=en) for your Gmail account.

>Note
>1. Email address should be stored in an environment variable named MAIL_ADDRESS.
>2. Application Password of that Gmail account should be stored in an environment variable named MAIL_PASSWORD.
>4. Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by WadadParker** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @WadadParker

**Comment by automatefreely** [comment]
@WadadParker Update?

**Comment by WadadParker** [comment]
> @WadadParker Update?

Have set up the Google code n library, sending you a PR

**Comment by coderatiiita** [comment]
claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by DikshantK2004** [comment]
claim
