### ISSUE TITLE
Update SubChannel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#54]
> Please note users/ admin are stored in channel/workspace level. In subchannels level we only divide the channels base on different topic.

Write the controller function to update a SubChannel in Channel. You will need to add respective checks in the function. The function should be written in controllers > subChannel.controller.js. The request and response structure are present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#update-subchannel).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user, workspace, channel, subchannel object are present in request and are all verified.
2. User is admin of Channel

**Also check all the details are in correct format and values.**

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by DikshantK2004** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004
