### ISSUE TITLE
Member user middleware for SubChannel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#58]
# Middleware for SubChannel Member Check

> Please note users/ admin are stored in channel/workspace level. In subchannels level we only divide the channels base on different topic.

1. Create a file in middleware folder named isSubChannelAdmin.middleware.js
2. write a middleware assuming the following request body
  
   ```json
   {
       "user": "mongoDB object of user"
   }
   ```

   and request param

    ```json
    {
         "id": "String"           -> MongoId of subchannel
    }
    ```

3. Assume user is already checked. You need to check subchannel exist or not.
4. If the user is not admin, send a response with status code 403 and message "You are not authorized to perform this action"
5. Add the channel, workspace, subchannel to the request body.
6. If the user is admin, call next() to pass the request to the next middleware.

> Tip: From the subchannel get the channel and then workspace. Check user is member of the channel. You can check other middleware for reference. All admins are member.

Also you need to check if all parameters are provides in correct form.

> Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by PranavBansal21** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic
