### ISSUE TITLE
Create Email Verification Template

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#6]
An email template is basically an HTML file which DOES NOT support javascript. You have to create an email template for an email that will be sent to users for verifying their email address. For that, they will receive a link in the mail that they will have to open. You can use styling and fill in temporary data for the user's name, verification link, etc.

You can be any creative with the design and structure of the email, as long as it serves the purpose.

How to submit?
- No need to claim, the issue is open for all.
- Create a file named ```verification-<Github Username>.html``` in the emailTemplate directory.
- No external CSS files are allowed, write the styling in the HTML file itself.
- Include the screenshot in your PR.
- You can find the color palette for the project Hitch-Backend here: [Figma File](https://www.figma.com/file/vyCC47vkwtmcoh1faTifkM/Hitch-Landing-Page?type=design&node-id=0-1&mode=design)

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by automatefreely** [comment]
No need to claim, the issue is open for all.

**Comment by meAyushSharma** [comment]
@automatefreely Please kindly review sir

**Comment by akshayw1** [comment]
@all Email template will be reviewed today and best one will get merge, and remaining may get partial point depending on design and responsiveness.

**Comment by akshayw1** [comment]
As mention the best PR will be merged and get full points, So the best PR is of @apoorva012 , and it will get merge remaining will get the partial points,
<img width="609" alt="image" src="https://github.com/opencodeiiita/Hitch-Backend/assets/120705327/b75e65c3-6a51-4b74-a9ad-291213a8eb82">
Happy Contributing!
