### ISSUE TITLE
Mongo warning resolution

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#63]
![image](https://github.com/opencodeiiita/Hitch-Backend/assets/105218991/445d0302-07b3-44d8-911e-78c2f4a1df53)

To get this warning run ```npm run dev``` after project setup
Resolve these warnings.

In PR describe what you did.

> comment to claim

**Comment by criticic** [comment]
claim

**Comment by rnavaneeth992** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by Karansenpai** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Karansenpai
