### ISSUE TITLE
Route for creating workspace

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#74]
Write and test route for creating a workspace.
Show the test results in form of screenshot.
If any necessary modification is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

> Comment to claim the issue.

**Comment by DikshantK2004** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004
