### ISSUE TITLE
Query User

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#75]
Write the controller function to query user from a channel whose username or email begins with the query parameter. You will need to add required checks in the function. The function should be written in controllers > user.controller.js. The request structure is present [here](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#query-user).

Also make sure all the information in the request "is provided" and "valid". If not give respective error responses.

## Assume the following
1. user object are present in request body and are all verified.

> Make sure to pull before starting your work.

For any **doubts** or **difficulty**, you can ping me on discord or comment here, I'll try to help you out as soon as possible.
Once completed, submit a pull request with the code.

Please comment to claim the issue.

**All the Best!!**

**Comment by criticic** [comment]
claim

**Comment by WadadParker** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic

**Comment by WadadParker** [comment]
c

**Comment by Jarviss77** [comment]
Claim
