### ISSUE TITLE
Update workspace and delete route

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#78]
Write and test route for updating and deleting a workspace.
Show the test results in form of screenshot.
If any necessary modification is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

> Comment to claim the issue.

**Comment by DikshantK2004** [comment]
Claim

**Comment by criticic** [comment]
claim

**Comment by WadadParker** [comment]
Claim

**Comment by PranavBansal21** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @DikshantK2004

**Comment by Jarviss77** [comment]
Claim
