### ISSUE TITLE
Route for creating Channel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#81]
Write and test route for creating a Channel.
Show the test results in form of screenshot.
If any necessary modification is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

**Comment by PranavBansal21** [comment]
claim

**Comment by criticic** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @criticic
