### ISSUE TITLE
Route for querying user

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#82]
Write and test route for [querying user](https://github.com/opencodeiiita/Hitch-Backend/blob/main/APIEndPoints.md#query-user) .
Show the test results in form of screenshot.
Controller present in user.controller.js
If any necessary modification is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

**Comment by criticic** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by Jarviss77** [comment]
Claim

**Comment by automatefreely** [comment]
> Cl

What do you mean?

**Comment by automatefreely** [comment]
Assigned to @Jarviss77
