### ISSUE TITLE
Get Channels routes

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#90]
Write and test route for getting all channels in workspace.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment **claim** to work on this issue.
Any problem ping me on discord or comment.

**Comment by TheDivineAurora** [comment]
claim

**Comment by TheDivineAurora** [comment]
please assign @automatefreely

**Comment by chiragmalik2612** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @TheDivineAurora
