### ISSUE TITLE
Add user to channel route

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#91]
Write and test route for adding user to Channel.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment claim to work on this issue.
Any problem ping me on discord or comment.

**Comment by Jarviss77** [comment]
Claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @chiragmalik2612

**Comment by PranavBansal21** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @PranavBansal21
