### ISSUE TITLE
Get users in channel route

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#93]
Write and test route for getting user from a Channel.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment claim to work on this issue.
Any problem ping me on discord or comment.

**Comment by TheDivineAurora** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Harshal5167** [comment]
claim

**Comment by DikshantK2004** [comment]
claim

**Comment by PranavBansal21** [comment]
Claim

**Comment by automatefreely** [comment]
Assigned to @PranavBansal21

**Comment by DikshantK2004** [comment]
claim

**Comment by saisreesatyassss** [comment]
claim
