### ISSUE TITLE
deleting a subchannel

### ISSUE THREAD

**Issue by automatefreely** [opencodeiiita/Hitch-Backend#99]
Write and test route for deleting a SubChannel.
Show the test results in form of screenshot.
If any necessary modification in controller is required, you are free.
Refer the API Doc present in APIEndPoints.md.
Use the necessary middleware.

Comment claim to work on this issue.
Any problem ping me on discord or comment.

**Comment by TheDivineAurora** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim

**Comment by Jarviss77** [comment]
claim

**Comment by PranavBansal21** [comment]
claim

**Comment by automatefreely** [comment]
Assigned to @Jarviss77

**Comment by automatefreely** [comment]
@Jarviss77 do a pull and also check this pr #101 as it affects what you are working on
